services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=levelup'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3306'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
